export const task = [
    "Configuración de herramientas (Jira, GitHub, etc.)",
    "Investigación sobre herramientas de IA (ChatGPT, Azure AI)",
    "Capacitación en Jira y GitHub",
    "Revisión de documentación e investigación sobre IA",
    "Definición del Product Backlog y objetivos iniciales",
    "Estudio de herramientas de IA y posibles aplicaciones",
    "Revisión de herramientas IA (ChatGPT, Azure AI)",
    "Configuración de Jira y Trello para equipo",
    "Ajustes de configuración y definición de roles",
    "Revisión de expectativas de Sprint 1",
    "Crear el Product Backlog y definir historias de usuario",
    "Estimación inicial de tareas en el Backlog",
    "Priorización de tareas y definición de sprints",
    "Refinamiento de historias de usuario",
    "Refinamiento del Product Backlog y ajustes",
    "Documentación de tareas y definición de aceptación",
    "Creación de la estrategia para Sprint 1",
    "Estudio de riesgos para Sprint 1",
    "Implementación del frontend (UI/UX inicial)",
    "Desarrollo de API para backend (autenticación)",
    "Diseño de bases de datos para el backend",
    "Revisión de estándares de código para frontend",
    "Implementación de primeras funcionalidades",
    "Programación de endpoints para obtener datos",
    "Implementación de pruebas unitarias para backend",
    "Sprint Review: Demostración de avances",
    "Retroalimentación de clientes y stakeholders",
    "Ajustes de funcionalidades según feedback",    
    "Revisión de tareas y planificación siguiente Sprint",
]


